openapi: 3.0.0
servers:
  - url: 'http://localhost:9000/api'
info:
  description: >-
    This is the OpenAPI definition of the blockchain services.
  version: 1.0.0
  title: OpenAPI blockchain services
tags:
  - name: payment
paths:
  /payment:
    post:
      tags:
        - payment
      summary: create new payment
      operationId: createPayment
      responses:
        '201': 
          description: payment created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentResponse'
        '400':
          description: bad request
      requestBody:
        $ref: '#/components/requestBodies/PaymentRequest'

components:
  requestBodies:
    PaymentRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PaymentRequest'
  schemas:
    PaymentRequest:
      title: Payment Request
      type: object
      required:
        - price_currency
        - price_amount
        - wallet
        - mode
      properties:
        price_currency:
          type: string
        price_amount:
          type: number
          format: double
        wallet:
          type: string
        mode:
          type: string
          enum: 
            - test
            - prod
    PaymentResponse:
      title: Payment Response
      type: object
      required:
        - payment_id
        - price_amount
        - price_currency
        - pay_address
        - pay_amount
        - pay_currency
        - payment_status
      properties:
        payment_id:
          type: string
          format: uuid
        price_amount:
         type: number
         format: double
        price_currency:
         type: string
         enum:
           - usd
           - chf
        pay_address:
         type: string
        pay_amount:
          type: string
        pay_currency:
         type: string
         enum:
           - eth
           - btc
        payment_status:
         type: string
         enum:
           - waiting